In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly as py

### Descripción de datos

Agregar definición de columnas

### Importación del dataset y creación del dataframe

In [13]:
df = pd.read_csv("../data/raw/Base_de_datos_Python_GRUPOA.csv", sep=";")

In [14]:
df

,Tipo de Solicitud,Nro. GEX,Fecha Vencimiento,Estado,Regional,Departamento,Tecnicos,Fecha de Solicitud,Fecha de Resolución,Fecha de Inscripción,...,profundidad,Diámetro,Caudal Ensayado,Nivel Estático,Nivel Dinámico,Caudal Máximo,Codigo Cuencas de nivel 2,Accion Solicitud,Tipo Resolución,Producción
0,Proyecto de Aprovechamiento,SGRH-00040200289-635.001,27/Mar/2011,Registrada,SALTO,SALTO,"Rodríguez, Jorge",18/set/2000,27/Mar/2001,NaN,...,55,"0,15","19,7",20,"37,5",NaN,14.0,Nueva,Autorización,7
1,Proyecto de Aprovechamiento,SGRH-00040200324-595.001,19/Oct/2010,Registrada,FRAY BENTOS,PAYSANDÚ,"Rodríguez, Jorge",10/Mar/2000,19/Oct/2000,25/Oct/2000,...,53,"0,15",9,25,29,NaN,18.0,Nueva,Autorización,4
2,Proyecto de Aprovechamiento,SGRH-00040200325-596.001,20/Oct/2010,Registrada,FRAY BENTOS,PAYSANDÚ,"Rodríguez, Jorge",10/Mar/2000,20/Oct/2000,27/Oct/2000,...,31,"0,15",25,2,5,NaN,18.0,Nueva,Autorización,4
3,Proyecto de Aprovechamiento,SGRH-00040200402-598.001,19/Oct/2010,Registrada,SAN JOSÉ,SAN JOSÉ,"Rodríguez, Jorge",11/Abr/2000,19/Oct/2000,25/Oct/2000,...,55,"0,15",20,28,"32,5",NaN,24.0,Nueva,Autorización,"2,5"
4,Proyecto de Aprovechamiento,SGRH-00040200414-609.001,10/Oct/2010,Registrada,SAN JOSÉ,CANELONES,"Rodríguez, Jorge",14/Abr/2000,10/Oct/2000,18/Oct/2000,...,64,"0,15","6,8","3,9","22,3",NaN,63.0,Nueva,Autorización,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5695,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5696,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df.shape

(5700, 38)

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5700 entries, 0 to 5699
Data columns (total 38 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Tipo de Solicitud              5159 non-null   str
 1   Nro. GEX                       5157 non-null   str
 2   Fecha Vencimiento              4700 non-null   str
 3   Estado                         5159 non-null   str
 4   Regional                       5157 non-null   str
 5   Departamento                   5157 non-null   str
 6   Tecnicos                       5142 non-null   str
 7   Fecha de Solicitud             5158 non-null   str
 8   Fecha de Resolución            4699 non-null   str
 9   Fecha de Inscripción           4653 non-null   str
 10  Caudal                         5113 non-null   str
 11  Volumen                        5127 non-null   str
 12  Uso                            5159 non-null   str
 13  Destino                        5159 non-null   str
 14  Latitud                        5159 non-null   str
 15  Longitud                       5159 non-null   str
 16  Mes Inicio                     5123 non-null   float64
 17  Mes Final                      5123 non-null   float64
 18  Horas x Año                    5121 non-null   float64
 19  Depto.-Padrón                  5145 non-null   str
 20  Tipo de Obra                   5158 non-null   str
 21  Id Solicitud                   5159 non-null   float64
 22  Codigo Cuencas de nivel 5      5152 non-null   float64
 23  Documento                      5158 non-null   str
 24  Sección y localidad catastral  3387 non-null   float64
 25  Cuencas de nivel 3             5152 non-null   str
 26  Curso a Utilizar               2575 non-null   str
 27  Tipo de acuifero               3128 non-null   str
 28  profundidad                    5115 non-null   str
 29  Diámetro                       5095 non-null   str
 30  Caudal Ensayado                4972 non-null   str
 31  Nivel Estático                 4808 non-null   str
 32  Nivel Dinámico                 4655 non-null   str
 33  Caudal Máximo                  0 non-null      float64
 34  Codigo Cuencas de nivel 2      5152 non-null   float64
 35  Accion Solicitud               5159 non-null   str
 36  Tipo Resolución                4693 non-null   str
 37  Producción                     1802 non-null   str
dtypes: float64(8), str(30)
memory usage: 3.2 MB

In [19]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Mes Inicio,5123.0,6.718915,5.342711,1.0,1.0,10.0,12.00,12.0
Mes Final,5123.0,9.740582,3.386649,0.0,10.0,11.0,12.00,12.0
Horas x Año,5121.0,3128.130443,1866.384298,1.0,1600.0,2880.0,4320.00,9000.0
Id Solicitud,5159.0,249482.421012,6255.075576,237902.0,244274.5,249362.0,254852.50,261225.0
Codigo Cuencas de nivel 5,5152.0,37711.344332,18888.650444,10105.0,22600.0,27400.0,58171.25,68710.0
Sección y localidad catastral,3387.0,5.623561,13.541791,0.0,2.0,4.0,7.00,746.0
Caudal Máximo,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Codigo Cuencas de nivel 2,5152.0,37.194682,18.909617,10.0,22.0,27.0,58.00,68.0